const data = [
  { key: `${Math.random()}`, done: true },
  { key: `${Math.random()}`, done: true },
  { key: `${Math.random()}`, done: true },
  { key: `${Math.random()}`, done: true },
  { key: `${Math.random()}`, done: true },
  { key: `${Math.random()}`, done: false },
  { key: `${Math.random()}`, done: true },
  { key: `${Math.random()}`, done: true },
  { key: `${Math.random()}`, done: true },
  { key: `${Math.random()}`, done: true },
  { key: `${Math.random()}`, done: true },
  { key: `${Math.random()}`, done: false },
  { key: `${Math.random()}`, done: true },
  { key: `${Math.random()}`, done: true },
  { key: `${Math.random()}`, done: false },
  { key: `${Math.random()}`, done: true },
  { key: `${Math.random()}`, done: true },
  { key: `${Math.random()}`, done: true },
  { key: `${Math.random()}`, done: false },
  { key: `${Math.random()}`, done: true },
  { key: `${Math.random()}`, done: true },
  { key: `${Math.random()}`, done: true },
  { key: `${Math.random()}`, done: true },
  { key: `${Math.random()}`, done: true },
  { key: `${Math.random()}`, done: true },
  { key: `${Math.random()}`, done: false },
  { key: `${Math.random()}`, done: true },
  { key: `${Math.random()}`, done: true },
  { key: `${Math.random()}`, done: true },
  { key: `${Math.random()}`, done: true }
]
export default data
